### ISSUE TITLE
DuGR 4 Beta: "Select layers" function only creates internal array/collection, does not select layers in the timeline

### ISSUE THREAD

**Issue by LarsJandel** [RxLaboratory/DuAEF_DuGR#29]
Well, currenty it's a bit too 🐱‍👤 mode maybe, as I can use the `Select Layers` function and apply other _DuGR_ functions on those layers, but I would prefer the layers being visibly selected in the timeline, too. 😅

Thanks Duduf for working on v4! 🙏

**Comment by Nico-Duduf** [comment]
I could add that as an option!
Will do!
Thanks for the idea :)

**Comment by LarsJandel** [comment]
...hm, just to make sure:
My intention was to report a bug, that `Select Layers` currently doesn't select the layers in the timeline. 😬

**Comment by Nico-Duduf** [comment]
Oh I thought you wanted DuGR to automatically select corresponding layers when you select groups ;)

Here it works correcly... Except locked layers which are not selected
We'll have to find what's going on. As it's a pretty simple function/code, I can't really see what could be wrong!

What's your OS? Ae version?

**Comment by LarsJandel** [comment]
Windows 10 - latest Beta & latest 2021
tried DuGR 3 again, which does select the layers in the timeline.

**Comment by LarsJandel** [comment]
![SelectLayersIssue](https://user-images.githubusercontent.com/32457827/127627674-da6da3e0-3248-4b7a-a837-42650d886faf.gif)

**Comment by Nico-Duduf** [comment]
Oooohhhh now I understand

The version I gave on discord had a bug I fixed just after posting it haha
Grab the version from the website it should work! sorry!

**Comment by Nico-Duduf** [comment]
I knew it would be cool to let people customize the color of the script :)

(You know you can even change Ae's blue?)

**Comment by LarsJandel** [comment]
![image](https://user-images.githubusercontent.com/32457827/127637321-f674a9b2-7d23-468d-8918-9a8d50a667dc.png)
😎
