### ISSUE TITLE
Changing the UI settings in the preferences doesn't not take effect

### ISSUE THREAD

**Issue by reneandritsch** [RxLaboratory/DuAEF_DuGR#34]
It seems that the choice of UI mode does not take effect immediately. I have to close and reopen the panel to see the preference executed.

V 4.0.0 Mac OS 11.5 AE 17.7.0

![ui-settings](https://user-images.githubusercontent.com/38455050/128775919-cf17a08a-ee6a-45aa-b700-f166ddfa8f2b.gif)

**Comment by Nico-Duduf** [comment]
For now I've just added an alert to warn the user he may have to restart the script; I have some issues I can't fix with the reload function I used in the current version of Duik....
I'll keep this issue open until I find a fix!

**Comment by Nico-Duduf** [comment]
Fixed!
