### ISSUE TITLE
Tool tip in the group tab missing for the icon with the question mark

### ISSUE THREAD

**Issue by reneandritsch** [RxLaboratory/DuAEF_DuGR#36]
In the group section between the icons “Add selected to groups“ and “Remove selected from groups” the one with the question mark does not invoke the tool tip on mouse over. Please see attached screen capture.

![tool-tip-missing](https://user-images.githubusercontent.com/38455050/128898947-b3f9a1d4-e4aa-46f5-8dd1-c6880feb2c5e.gif)

**Comment by Nico-Duduf** [comment]
fixed!
Thanks!

**Comment by reneandritsch** [comment]
Thanks!
